python ./lime/main.py \
--model_path /home/pureblackkkk/b2t-master/model/best_model_Waterbirds_erm.pth \
--img_data_dir /home/pureblackkkk/my_volume/concept-lime-data/revert_waterbird_concept_class_1000_Feb_14/waterbird_best_model_Waterbirds_erm_waterbird_without_class \
--csv_path /home/pureblackkkk/concept-lime/data/disturb_waterbird_concept_class_1000_Feb_14/waterbird_best_model_Waterbirds_erm_waterbird.csv \
--batch_size 10 \
--num_workers 4 \
--add_cos_sim_weights \
--dataset_name WaterBird \
--class_name all \
--meta_data_path /home/pureblackkkk/b2t-master/data/cub/data/waterbird_complete95_forest2water2/metadata.csv \
--img_src_dir /home/pureblackkkk/b2t-master/data/cub/data/waterbird_complete95_forest2water2/ \
--gradcam